In [1]:
import pandas as pd
from astropy.table import Table

In [3]:
df = pd.read_csv("../class-pne-peimbert.csv")

In [4]:
df

,recno,Name,PNG,He/H,n_He/H,r_He/H,lg(O/H)+12,r_lg(O/H)+12,lg(N/H)+12,r_lg(N/H)+12,...,p(typeI),p(typeIIa),p(typeIIb),p(typeIII),p(typeIV),Pre-class,Post-class,SimbadName,_RA,_DE
0,1,A4,144.3-15.5,NaN,,21,NaN,21,NaN,21,...,0.00,0.00,0.00,0.00,1.00,indef.,IV,PN G144.3-15.5,41.34861,42.55137
1,2,A12,198.6-06.3,0.119,,3,8.93,3,8.06,3,...,0.00,0.11,0.67,0.22,0.00,IIbD,IIb,PN G198.6-06.3,90.58352,9.65391
2,3,A18,216.0-00.2,0.152,,3,7.99,3,7.97,3,...,0.98,0.02,0.00,0.00,0.00,ID,I,PN G216.0-00.2,104.06108,-2.88550
3,4,A20,214.9+07.8,0.125,,3,8.80,3,NaN,3,...,0.00,0.78,0.16,0.06,0.00,(I/IIa)D*,IIa,PN G214.9+07.8,110.74060,1.75912
4,5,A24,217.1+14.7,NaN,,21,NaN,21,NaN,21,...,1.00,0.00,0.00,0.00,0.00,indef.,I,PN G217.1+14.7,117.90646,3.00583
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471,472,Vy2-1,007.0-06.8,0.145,,6,8.94,6,9.04,6,...,0.00,1.00,0.00,0.00,0.00,VF,IIa,PN G007.0-06.8,276.99835,-26.11341
472,473,Vy2-2,045.4-02.7,0.104,,"13,21,23",8.34,"13,16,23",7.53,"13,23",...,0.00,0.00,0.00,0.99,0.01,IIbC/(III/IV)B,III,PN G045.4-02.7,291.09262,9.89907
473,474,Y-c2-5,240.3+07.0,0.071,,3,9.05,3,NaN,3,...,0.00,0.02,0.07,0.91,0.00,(IIa/IIb)D*,III,PN G240.3+07.0,122.67345,-20.52560
474,475,Y-c2-32,013.7-10.6,0.088,,6,8.59,6,7.59,6,...,0.00,0.00,0.44,0.43,0.13,(IIb/III/IV)D,IIb,PN G013.7-10.6,283.87750,-21.82750
475,476,Ym29,205.1+14.2,NaN,,16,8.53,16,NaN,16,...,0.90,0.10,0.00,0.00,0.00,indef.,I,PN G205.1+14.2,112.26128,13.24688